In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("newstudent.csv")
df

    rollno name    course
0      101   jan  science
1      102   feb     math
2      103   mar       gk
3      104   apr  science
4      105   may     math
5      106   jun       gk
6      107   jul  science
7      108   aug     math
8      109   sep       gk
9      110   oct  science
10     111   nov     math
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [3]:
df.head()

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk
3     104   apr  science
4     105   may     math

In [4]:
df.head(3)

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk

In [5]:
df.tail(3)

    rollno name    course
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [6]:
df.shape[0]# row

14

In [7]:
df.shape[1] #column

3

In [8]:
df.columns

Index(['rollno', 'name ', 'course'], dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [10]:
df["course"]

0     science
1        math
2          gk
3     science
4        math
5          gk
6     science
7        math
8          gk
9     science
10       math
11         gk
12    science
13       math
Name: course, dtype: object

In [11]:
df.describe()

         rollno
count   14.0000
mean   107.5000
std      4.1833
min    101.0000
25%    104.2500
50%    107.5000
75%    110.7500
max    114.0000

In [12]:
df.describe(include="all")

          rollno name    course
count    14.0000    14       14
unique       NaN    12        3
top          NaN   jan  science
freq         NaN     2        5
mean    107.5000   NaN      NaN
std       4.1833   NaN      NaN
min     101.0000   NaN      NaN
25%     104.2500   NaN      NaN
50%     107.5000   NaN      NaN
75%     110.7500   NaN      NaN
max     114.0000   NaN      NaN

In [13]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [14]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [15]:
A=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
dt=pd.DataFrame(A)
print(dt.T)

     0    1
0  Sun  Jan
1  Mon  Feb
2  Tue  Mar
3  Wed  Apr

In [16]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt)

     0    1
0  Sun  Mon
1  Tue  Wed
2  Jan  Feb
3  Mar  Apr

In [17]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A)
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [18]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=['weekdays','monthname'])
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [19]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=["s1","s2","s3","s4"])
print(dt)

Empty DataFrame
Columns: [s1, s2, s3, s4]
Index: []

In [20]:
# ager string huaa to => count,unique,top,freq

In [21]:
# A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
# dt=pd.DataFrame(A)
# print(dt.columns())

In [22]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      object
 1   1       4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes
None

In [23]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.describe())

          0    1
count     4    4
unique    4    4
top     Sun  Mon
freq      1    1

In [24]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.max())

0    Tue
1    Wed
dtype: object

In [25]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.min())

0    Jan
1    Apr
dtype: object

In [26]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.isnull())

       0      1
0  False  False
1  False  False
2  False  False
3  False  False

In [27]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [28]:
j={"Rno":[101,1002,103,104,105],"marks":[89,55,96,88,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101     89
1  1002     55
2   103     96
3   104     88
4   105     67

In [29]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [30]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull())

     Rno  marks
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False

In [31]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull().count())

Rno      5
marks    5
dtype: int64

In [32]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,25000,20000,40000]}
df=pd.DataFrame(df)
print(df)
print(df.isnull())

     Name  salary
0    anup   20000
1    ravi   35000
2   sohan   25000
3   punit   20000
4  deepak   40000
    Name  salary
0  False   False
1  False   False
2  False   False
3  False   False
4  False   False

In [33]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated())

     Name   salary
0    anup  20000.0
1    ravi  35000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [34]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated().sum())

     Name   salary
0    anup  20000.0
1    ravi  35000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0

In [35]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated())

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0    False
1    False
2    False
3     True
4    False
dtype: bool

In [36]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated().sum())

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
1

In [37]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"})

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

     Name  package
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

In [38]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"}, inplace=True)

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

In [39]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"}, inplace=True)
df["package"].var()

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

0.0

In [40]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
# df['Name']
# df['salary']


# df.rename(columns={"salary": "package"}, inplace=True)
# df["package"].var()
df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]
df

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

     Name   salary    city
0    anup  20000.0  Bhopal
1   punit  20000.0  indore
2   sohan      NaN  Bhopal
3   punit  20000.0  ujjain
4  deepak      NaN  nagpur

In [41]:
tp={"Name":"Amit","marks":87}
tp

{'Name': 'Amit', 'marks': 87}

In [42]:
tp={"Name":"Amit","marks":87}
tp["name"]=20
tp

{'Name': 'Amit', 'marks': 87, 'name': 20}

In [43]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]
# df.head(2)
df[0:2]
df.set_index('Name')

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

         salary    city
Name
anup    20000.0  Bhopal
punit   20000.0  indore
sohan       NaN  Bhopal
punit   20000.0  ujjain
deepak      NaN  nagpur

In [44]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]

df = df.set_index('Name')
df[0:3]

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [45]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]

df = df.set_index('Name')
df["anup":"sohan"]

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [46]:
df.loc["anup":"sohan"] # label Based searching # non interger

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [47]:
df.iloc[0:2] # index(integer) based searching

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore

In [48]:
A = {"Name":["Govind","Rihaan","Himesh","Tanishq"],"salary":[45000,30000,20000,25000], "Age":[20,26,23,90]}
df=pd.DataFrame(A)
print(df)
df
df.loc[[0,1],["salary","Age"]]
B = df.iloc[0:2,1:3]
B

      Name  salary  Age
0   Govind   45000   20
1   Rihaan   30000   26
2   Himesh   20000   23
3  Tanishq   25000   90

   salary  Age
0   45000   20
1   30000   26

In [49]:
df.columns

Index(['Name', 'salary', 'Age'], dtype='object')

In [50]:
df["salary"]

0    45000
1    30000
2    20000
3    25000
Name: salary, dtype: int64

In [51]:
df["salary"].astype(float)

0    45000.0
1    30000.0
2    20000.0
3    25000.0
Name: salary, dtype: float64

In [52]:
df["salary"]=df["salary"].astype(float)
df

      Name   salary  Age
0   Govind  45000.0   20
1   Rihaan  30000.0   26
2   Himesh  20000.0   23
3  Tanishq  25000.0   90

In [53]:
df["salary"].astype(int)

0    45000
1    30000
2    20000
3    25000
Name: salary, dtype: int64

# Between Function

In [54]:
df["salary"]=df["salary"].astype(float)
df[df["salary"].between(10000,30000)]

      Name   salary  Age
1   Rihaan  30000.0   26
2   Himesh  20000.0   23
3  Tanishq  25000.0   90

In [55]:
df["salary"]=df["salary"].astype(float)
df[df["Name"].between("Rihaan","Tanishq")]

      Name   salary  Age
1   Rihaan  30000.0   26
3  Tanishq  25000.0   90

In [56]:
df["Name"] = df["Name"].replace("Himesh","Somesh")
df

      Name   salary  Age
0   Govind  45000.0   20
1   Rihaan  30000.0   26
2   Somesh  20000.0   23
3  Tanishq  25000.0   90

In [57]:
df[df["Name"].between("Rihaan","Tanishq")]

      Name   salary  Age
1   Rihaan  30000.0   26
2   Somesh  20000.0   23
3  Tanishq  25000.0   90

### Drop function in duplicate

In [60]:
B = {"Name":[None,"Rihaan","Himesh","Tanishq"],"salary":[None,30000,20000,None], "Age":[None,26,23,90]}
df=pd.DataFrame(B)
df
df.dropna() # Drop entire row where it found null value 
df
df.dropna(how="all")

      Name   salary   Age
1   Rihaan  30000.0  26.0
2   Himesh  20000.0  23.0
3  Tanishq      NaN  90.0