In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("newstudent.csv")
df

    rollno name    course
0      101   jan  science
1      102   feb     math
2      103   mar       gk
3      104   apr  science
4      105   may     math
5      106   jun       gk
6      107   jul  science
7      108   aug     math
8      109   sep       gk
9      110   oct  science
10     111   nov     math
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [11]:
df.head()

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk
3     104   apr  science
4     105   may     math

In [12]:
df.head(3)

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk

In [14]:
df.tail(3)

    rollno name    course
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [16]:
df.shape[0]# row

14

In [17]:
df.shape[1] #column

3

In [18]:
df.columns

Index(['rollno', 'name ', 'course'], dtype='object')

In [19]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [22]:
df["course"]

0     science
1        math
2          gk
3     science
4        math
5          gk
6     science
7        math
8          gk
9     science
10       math
11         gk
12    science
13       math
Name: course, dtype: object

In [24]:
df.describe()

         rollno
count   14.0000
mean   107.5000
std      4.1833
min    101.0000
25%    104.2500
50%    107.5000
75%    110.7500
max    114.0000

In [25]:
df.describe(include="all")

          rollno name    course
count    14.0000    14       14
unique       NaN    12        3
top          NaN   jan  science
freq         NaN     2        5
mean    107.5000   NaN      NaN
std       4.1833   NaN      NaN
min     101.0000   NaN      NaN
25%     104.2500   NaN      NaN
50%     107.5000   NaN      NaN
75%     110.7500   NaN      NaN
max     114.0000   NaN      NaN

In [26]:
df.occupation.describe()

AttributeError: 'DataFrame' object has no attribute 'occupation'