In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("newstudent.csv")
df

    rollno name    course
0      101   jan  science
1      102   feb     math
2      103   mar       gk
3      104   apr  science
4      105   may     math
5      106   jun       gk
6      107   jul  science
7      108   aug     math
8      109   sep       gk
9      110   oct  science
10     111   nov     math
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [11]:
df.head()

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk
3     104   apr  science
4     105   may     math

In [12]:
df.head(3)

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk

In [14]:
df.tail(3)

    rollno name    course
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [16]:
df.shape[0]# row

14

In [17]:
df.shape[1] #column

3

In [18]:
df.columns

Index(['rollno', 'name ', 'course'], dtype='object')

In [19]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [22]:
df["course"]

0     science
1        math
2          gk
3     science
4        math
5          gk
6     science
7        math
8          gk
9     science
10       math
11         gk
12    science
13       math
Name: course, dtype: object

In [24]:
df.describe()

         rollno
count   14.0000
mean   107.5000
std      4.1833
min    101.0000
25%    104.2500
50%    107.5000
75%    110.7500
max    114.0000

In [25]:
df.describe(include="all")

          rollno name    course
count    14.0000    14       14
unique       NaN    12        3
top          NaN   jan  science
freq         NaN     2        5
mean    107.5000   NaN      NaN
std       4.1833   NaN      NaN
min     101.0000   NaN      NaN
25%     104.2500   NaN      NaN
50%     107.5000   NaN      NaN
75%     110.7500   NaN      NaN
max     114.0000   NaN      NaN

In [8]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [22]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [27]:
A=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
dt=pd.DataFrame(A)
print(dt.T)

     0    1
0  Sun  Jan
1  Mon  Feb
2  Tue  Mar
3  Wed  Apr

In [36]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt)

     0    1
0  Sun  Mon
1  Tue  Wed
2  Jan  Feb
3  Mar  Apr

In [42]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A)
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [44]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=['weekdays','monthname'])
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [45]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=["s1","s2","s3","s4"])
print(dt)

Empty DataFrame
Columns: [s1, s2, s3, s4]
Index: []

In [48]:
# ager string huaa to => count,unique,top,freq

In [62]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.columns())

TypeError: 'RangeIndex' object is not callable

In [57]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      object
 1   1       4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes
None

In [53]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.describe())

          0    1
count     4    4
unique    4    4
top     Sun  Mon
freq      1    1

In [59]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.max())

0    Tue
1    Wed
dtype: object

In [60]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.min())

0    Jan
1    Apr
dtype: object

In [61]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.isnull())

       0      1
0  False  False
1  False  False
2  False  False
3  False  False

In [63]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [64]:
j={"Rno":[101,1002,103,104,105],"marks":[89,55,96,88,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101     89
1  1002     55
2   103     96
3   104     88
4   105     67

In [65]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [66]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull())

     Rno  marks
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False

In [72]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull().count())

Rno      5
marks    5
dtype: int64