In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("newstudent.csv")
df

    rollno name    course
0      101   jan  science
1      102   feb     math
2      103   mar       gk
3      104   apr  science
4      105   may     math
5      106   jun       gk
6      107   jul  science
7      108   aug     math
8      109   sep       gk
9      110   oct  science
10     111   nov     math
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [4]:
df.head()

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk
3     104   apr  science
4     105   may     math

In [5]:
df.head(3)

   rollno name    course
0     101   jan  science
1     102   feb     math
2     103   mar       gk

In [6]:
df.tail(3)

    rollno name    course
11     112   dec       gk
12     113   jan  science
13     114   feb     math

In [7]:
df.shape[0]# row

14

In [8]:
df.shape[1] #column

3

In [9]:
df.columns

Index(['rollno', 'name ', 'course'], dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=14, step=1)

In [11]:
df["course"]

0     science
1        math
2          gk
3     science
4        math
5          gk
6     science
7        math
8          gk
9     science
10       math
11         gk
12    science
13       math
Name: course, dtype: object

In [12]:
df.describe()

         rollno
count   14.0000
mean   107.5000
std      4.1833
min    101.0000
25%    104.2500
50%    107.5000
75%    110.7500
max    114.0000

In [13]:
df.describe(include="all")

          rollno name    course
count    14.0000    14       14
unique       NaN    12        3
top          NaN   jan  science
freq         NaN     2        5
mean    107.5000   NaN      NaN
std       4.1833   NaN      NaN
min     101.0000   NaN      NaN
25%     104.2500   NaN      NaN
50%     107.5000   NaN      NaN
75%     110.7500   NaN      NaN
max     114.0000   NaN      NaN

In [14]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [15]:
List=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
data=pd.DataFrame(List)
data

     0    1    2    3
0  Sun  Mon  Tue  Wed
1  Jan  Feb  Mar  Apr

In [16]:
A=[["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]
dt=pd.DataFrame(A)
print(dt.T)

     0    1
0  Sun  Jan
1  Mon  Feb
2  Tue  Mar
3  Wed  Apr

In [17]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt)

     0    1
0  Sun  Mon
1  Tue  Wed
2  Jan  Feb
3  Mar  Apr

In [18]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A)
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [19]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=['weekdays','monthname'])
print(dt)

  weekdays monthname
0      Sun       Jan
1      Mon       Feb
2      Tue       Mar
3      Wed       Apr

In [20]:
A={"weekdays":["Sun","Mon","Tue","Wed"],"monthname":["Jan","Feb","Mar","Apr"]}
dt=pd.DataFrame(A,columns=["s1","s2","s3","s4"])
print(dt)

Empty DataFrame
Columns: [s1, s2, s3, s4]
Index: []

In [21]:
# ager string huaa to => count,unique,top,freq

In [22]:
# A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
# dt=pd.DataFrame(A)
# print(dt.columns())

In [23]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4 non-null      object
 1   1       4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes
None

In [24]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.describe())

          0    1
count     4    4
unique    4    4
top     Sun  Mon
freq      1    1

In [25]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.max())

0    Tue
1    Wed
dtype: object

In [26]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.min())

0    Jan
1    Apr
dtype: object

In [27]:
A=np.array([["Sun","Mon","Tue","Wed"],["Jan","Feb","Mar","Apr"]]).reshape(4,2)
dt=pd.DataFrame(A)
print(dt.isnull())

       0      1
0  False  False
1  False  False
2  False  False
3  False  False

In [28]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [29]:
j={"Rno":[101,1002,103,104,105],"marks":[89,55,96,88,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101     89
1  1002     55
2   103     96
3   104     88
4   105     67

In [30]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df)

    Rno  marks
0   101   89.0
1  1002    NaN
2   103   96.0
3   104    NaN
4   105   67.0

In [31]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull())

     Rno  marks
0  False  False
1  False   True
2  False  False
3  False   True
4  False  False

In [32]:
j={"Rno":[101,1002,103,104,105],"marks":[89,None,96,None,67]}
df=pd.DataFrame(j)
print(df.isnull().count())

Rno      5
marks    5
dtype: int64

In [33]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,25000,20000,40000]}
df=pd.DataFrame(df)
print(df)
print(df.isnull())

     Name  salary
0    anup   20000
1    ravi   35000
2   sohan   25000
3   punit   20000
4  deepak   40000
    Name  salary
0  False   False
1  False   False
2  False   False
3  False   False
4  False   False

In [34]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated())

     Name   salary
0    anup  20000.0
1    ravi  35000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [35]:
df={"Name":["anup","ravi","sohan","punit","deepak"],"salary":[20000,35000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated().sum())

     Name   salary
0    anup  20000.0
1    ravi  35000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0

In [36]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated())

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
0    False
1    False
2    False
3     True
4    False
dtype: bool

In [37]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
print(df.isnull().sum())
print(df.duplicated().sum())

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN
Name      0
salary    2
dtype: int64
1

In [38]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"})

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

     Name  package
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

In [39]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"}, inplace=True)

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

In [40]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
df['Name']
df['salary']

df.rename(columns={"salary": "package"}, inplace=True)
df["package"].var()

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

0.0

In [41]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)
# df['Name']
# df['salary']


# df.rename(columns={"salary": "package"}, inplace=True)
# df["package"].var()
df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]
df

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

     Name   salary    city
0    anup  20000.0  Bhopal
1   punit  20000.0  indore
2   sohan      NaN  Bhopal
3   punit  20000.0  ujjain
4  deepak      NaN  nagpur

In [42]:
tp={"Name":"Amit","marks":87}
tp

{'Name': 'Amit', 'marks': 87}

In [43]:
tp={"Name":"Amit","marks":87}
tp["name"]=20
tp

{'Name': 'Amit', 'marks': 87, 'name': 20}

In [44]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]
# df.head(2)
df[0:2]
df.set_index('Name')

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

         salary    city
Name
anup    20000.0  Bhopal
punit   20000.0  indore
sohan       NaN  Bhopal
punit   20000.0  ujjain
deepak      NaN  nagpur

In [45]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]

df = df.set_index('Name')
df[0:3]

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [46]:
df={"Name":["anup","punit","sohan","punit","deepak"],"salary":[20000,20000,None,20000,None]}
df=pd.DataFrame(df)
print(df)

df["city"]=["Bhopal","indore","Bhopal","ujjain","nagpur"]

df = df.set_index('Name')
df["anup":"sohan"]

     Name   salary
0    anup  20000.0
1   punit  20000.0
2   sohan      NaN
3   punit  20000.0
4  deepak      NaN

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [47]:
df.loc["anup":"sohan"] # label Based searching # non interger

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore
sohan      NaN  Bhopal

In [48]:
df.iloc[0:2] # index(integer) based searching

        salary    city
Name
anup   20000.0  Bhopal
punit  20000.0  indore

In [49]:
A = {"Name":["Govind","Rihaan","Himesh","Tanishq"],"salary":[45000,30000,20000,25000], "Age":[20,26,23,90]}
df=pd.DataFrame(A)
print(df)
df
df.loc[[0,1],["salary","Age"]]
B = df.iloc[0:2,1:3]
B

      Name  salary  Age
0   Govind   45000   20
1   Rihaan   30000   26
2   Himesh   20000   23
3  Tanishq   25000   90

   salary  Age
0   45000   20
1   30000   26

In [50]:
df.columns

Index(['Name', 'salary', 'Age'], dtype='object')

In [51]:
df["salary"]

0    45000
1    30000
2    20000
3    25000
Name: salary, dtype: int64

In [52]:
df["salary"].astype(float)

0    45000.0
1    30000.0
2    20000.0
3    25000.0
Name: salary, dtype: float64

In [53]:
df["salary"]=df["salary"].astype(float)
df

      Name   salary  Age
0   Govind  45000.0   20
1   Rihaan  30000.0   26
2   Himesh  20000.0   23
3  Tanishq  25000.0   90

In [54]:
df["salary"].astype(int)

0    45000
1    30000
2    20000
3    25000
Name: salary, dtype: int64

# Between Function

In [55]:
df["salary"]=df["salary"].astype(float)
df[df["salary"].between(10000,30000)]

      Name   salary  Age
1   Rihaan  30000.0   26
2   Himesh  20000.0   23
3  Tanishq  25000.0   90

In [56]:
df["salary"]=df["salary"].astype(float)
df[df["Name"].between("Rihaan","Tanishq")]

      Name   salary  Age
1   Rihaan  30000.0   26
3  Tanishq  25000.0   90

In [57]:
df["Name"] = df["Name"].replace("Himesh","Somesh")
df

      Name   salary  Age
0   Govind  45000.0   20
1   Rihaan  30000.0   26
2   Somesh  20000.0   23
3  Tanishq  25000.0   90

In [58]:
df[df["Name"].between("Rihaan","Tanishq")]

      Name   salary  Age
1   Rihaan  30000.0   26
2   Somesh  20000.0   23
3  Tanishq  25000.0   90

### Drop function in duplicate

In [59]:
B = {"Name":[None,"Rihaan","Himesh","Tanishq"],"salary":[None,30000,20000,None], "Age":[None,26,23,90]}
df=pd.DataFrame(B)
df
df.dropna() # Drop entire row where it found null value 
df
df.dropna(how="all")

      Name   salary   Age
1   Rihaan  30000.0  26.0
2   Himesh  20000.0  23.0
3  Tanishq      NaN  90.0

In [60]:
A = {"Name":["Govind","Rihaan","Himesh","Tanishq"], "Age":[20,None,23,90]}
df=pd.DataFrame(A)
print(df)
df

      Name   Age
0   Govind  20.0
1   Rihaan   NaN
2   Himesh  23.0
3  Tanishq  90.0

      Name   Age
0   Govind  20.0
1   Rihaan   NaN
2   Himesh  23.0
3  Tanishq  90.0

In [61]:
df.dropna()

      Name   Age
0   Govind  20.0
2   Himesh  23.0
3  Tanishq  90.0

In [62]:
df.dropna(how="all")

      Name   Age
0   Govind  20.0
1   Rihaan   NaN
2   Himesh  23.0
3  Tanishq  90.0

In [63]:
A = {"Name":["Govind",None,"Himesh","Tanishq"], "Age":[None,None,23,90],"Salary":[20000,30000,40000,5000]}
df=pd.DataFrame(A)
print(df)
df.dropna(thresh=1)

      Name   Age  Salary
0   Govind   NaN   20000
1     None   NaN   30000
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

      Name   Age  Salary
0   Govind   NaN   20000
1     None   NaN   30000
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

In [64]:
df.dropna(thresh=0)

      Name   Age  Salary
0   Govind   NaN   20000
1     None   NaN   30000
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

In [65]:
df.dropna(thresh=1)

      Name   Age  Salary
0   Govind   NaN   20000
1     None   NaN   30000
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

In [66]:
df.dropna(thresh=2)

      Name   Age  Salary
0   Govind   NaN   20000
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

In [67]:
df.dropna(thresh=3)

      Name   Age  Salary
2   Himesh  23.0   40000
3  Tanishq  90.0    5000

In [68]:
A = {"Name":["Govind",None,"Himesh","Tanishq","Anuraj","vijay"], "Age":[None,None,23,90,23,21],"Salary":[2000,3000,4000,5000,None,18000]}
df=pd.DataFrame(A)
print(df)
df.fillna(-1)

      Name   Age   Salary
0   Govind   NaN   2000.0
1     None   NaN   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0      NaN
5    vijay  21.0  18000.0

      Name   Age   Salary
0   Govind  -1.0   2000.0
1       -1  -1.0   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0     -1.0
5    vijay  21.0  18000.0

In [69]:
A = {"Name":["Govind",None,"Himesh","Tanishq","Anuraj","vijay"], "Age":[None,None,23,90,23,21],"Salary":[2000,3000,4000,5000,None,18000]}
df=pd.DataFrame(A)
print(df)
df.fillna(-99)

      Name   Age   Salary
0   Govind   NaN   2000.0
1     None   NaN   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0      NaN
5    vijay  21.0  18000.0

      Name   Age   Salary
0   Govind -99.0   2000.0
1      -99 -99.0   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0    -99.0
5    vijay  21.0  18000.0

In [70]:
A = {"Name":["Govind",None,"Himesh","Tanishq","Anuraj","vijay"], "Age":[None,None,23,90,23,21],"Salary":[2000,3000,4000,5000,None,18000]}
df=pd.DataFrame(A)
print(df)
df.fillna(-9)

      Name   Age   Salary
0   Govind   NaN   2000.0
1     None   NaN   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0      NaN
5    vijay  21.0  18000.0

      Name   Age   Salary
0   Govind  -9.0   2000.0
1       -9  -9.0   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0     -9.0
5    vijay  21.0  18000.0

In [71]:
A = {"Name":["Govind",None,"Himesh","Tanishq","Anuraj","vijay"], "Age":[None,None,23,90,23,21],"Salary":[2000,3000,4000,5000,None,18000]}
df=pd.DataFrame(A)
print(df)
df.fillna(-11111111111111111111111)

      Name   Age   Salary
0   Govind   NaN   2000.0
1     None   NaN   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4   Anuraj  23.0      NaN
5    vijay  21.0  18000.0

                       Name           Age        Salary
0                    Govind -1.111111e+22  2.000000e+03
1  -11111111111111111111111 -1.111111e+22  3.000000e+03
2                    Himesh  2.300000e+01  4.000000e+03
3                   Tanishq  9.000000e+01  5.000000e+03
4                    Anuraj  2.300000e+01 -1.111111e+22
5                     vijay  2.100000e+01  1.800000e+04

In [72]:
A = {"Name":["Govind",None,"Himesh","Tanishq",None,"vijay"], "Age":[None,None,23,90,23,21],"Salary":[2000,3000,4000,5000,None,18000]}
df=pd.DataFrame(A)
print(df)
df.fillna(-31)

      Name   Age   Salary
0   Govind   NaN   2000.0
1     None   NaN   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4     None  23.0      NaN
5    vijay  21.0  18000.0

      Name   Age   Salary
0   Govind -31.0   2000.0
1      -31 -31.0   3000.0
2   Himesh  23.0   4000.0
3  Tanishq  90.0   5000.0
4      -31  23.0    -31.0
5    vijay  21.0  18000.0

In [73]:
A={"Name":["Amit","Sunil","Ravi","Joy","Deepak"],"Age":[23,21,25,27,28]}
df=pd.DataFrame(A)
df

     Name  Age
0    Amit   23
1   Sunil   21
2    Ravi   25
3     Joy   27
4  Deepak   28

In [74]:
# Apply () is USED to filter the data by passing argument as function 
print(df[["Age"]].apply(sum))

Age    124
dtype: int64

In [75]:
print(df[["Age"]].apply(max))

Age    28
dtype: int64

In [76]:
print(df[["Age"]].apply(min))

Age    21
dtype: int64

In [77]:
h=[10,20,30,40,50]
df=pd.DataFrame(h)
df

    0
0  10
1  20
2  30
3  40
4  50

In [78]:
A = {"Name":["amit",None,"ronak"], "Age":[None,None,24], "Salary":[20000, 30000, 40000]}
df = pd.DataFrame(A)

df.dropna(how = "all")
df

    Name   Age  Salary
0   amit   NaN   20000
1   None   NaN   30000
2  ronak  24.0   40000

In [79]:
B = {"Name":["amit",None,"ronak"], "Age":[None,None,24], "Salary":[20000, 30000, 40000]}
df = pd.DataFrame(B)
df.dropna(thresh=2)   # finds non-null values in dataframe and removes the rows with non null values below threshold (eg.: will check if non-null values are below 2 it removes that row)

    Name   Age  Salary
0   amit   NaN   20000
2  ronak  24.0   40000

In [80]:
C = {"Name":["amit",None,"ronak","Nilesh","Shubh"], "Age":[None,None,24,21,26], "Salary":[20000, 30000, 40000, None, 47000]}
df = pd.DataFrame(C)
df.fillna(-1)

     Name   Age   Salary
0    amit  -1.0  20000.0
1      -1  -1.0  30000.0
2   ronak  24.0  40000.0
3  Nilesh  21.0     -1.0
4   Shubh  26.0  47000.0

In [81]:
D = {"Name":["Roni","Joy",None,"Roni","Dev"], "Age":[21,24,None,22,28], "Result":["p","p",None,"p","f"]}
dt = pd.DataFrame(D)
dt['Name'].fillna('Not filled')

0          Roni
1           Joy
2    Not filled
3          Roni
4           Dev
Name: Name, dtype: object

In [82]:
dt['Name'] = dt['Name'].fillna("Not filled")
dt['Age'] = dt['Age'].fillna(value = dt['Age'].mean())
dt['Result'] = dt['Result'].fillna(value = dt['Result'].mode()[0])

In [83]:
E = {"Name":["Roni","Joy",None,"Roni","Dev"], "Age":[21,24,None,22,28], "Result":["f","f",None,"p","f"]}
dt2 = pd.DataFrame(E)
dt2

   Name   Age Result
0  Roni  21.0      f
1   Joy  24.0      f
2  None   NaN   None
3  Roni  22.0      p
4   Dev  28.0      f

In [84]:
dt2['Result'].fillna(method='ffill')    
# It does forward fill, fills with upper value

C:\Users\Asus\AppData\Local\Temp\ipykernel_19192\156061129.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dt2['Result'].fillna(method='ffill')

0    f
1    f
2    f
3    p
4    f
Name: Result, dtype: object

In [85]:
dt2['Result'].fillna(method ='bfill')      # It does backward fill, fills with below value

C:\Users\Asus\AppData\Local\Temp\ipykernel_19192\3840327392.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dt2['Result'].fillna(method ='bfill')      # It does backward fill, fills with below value

0    f
1    f
2    p
3    p
4    f
Name: Result, dtype: object

In [86]:
F = {"Name":["Roni","Joy",None,"Roni","Dev"], "Age":[21,24,None,21,28], "Result":["f","p",None,"f","p"]}

dt3 = pd.DataFrame(F)

print(dt3)


dt3.drop_duplicates()

   Name   Age Result
0  Roni  21.0      f
1   Joy  24.0      p
2  None   NaN   None
3  Roni  21.0      f
4   Dev  28.0      p

   Name   Age Result
0  Roni  21.0      f
1   Joy  24.0      p
2  None   NaN   None
4   Dev  28.0      p

In [87]:
dt3.drop(columns = ['Result','Name'])

    Age
0  21.0
1  24.0
2   NaN
3  21.0
4  28.0

In [88]:
h=[10,20,30,40,50]
df=pd.DataFrame(h)
df**2

      0
0   100
1   400
2   900
3  1600
4  2500

In [89]:
h=[10,20,30,40,50]
df=pd.DataFrame(h)
df.apply(lambda K :K*K*K)

        0
0    1000
1    8000
2   27000
3   64000
4  125000

In [90]:
h=[10,20,30,40,50]
df=pd.DataFrame(h)
df.apply(lambda K :K/2)

      0
0   5.0
1  10.0
2  15.0
3  20.0
4  25.0

In [91]:
h=[10,20,30,40,50,51]
df=pd.DataFrame(h)
df.apply(lambda K :K%2==0) # lambda fuction is called anonymous Function ,It supports single line Statement

       0
0   True
1   True
2   True
3   True
4   True
5  False

In [92]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,50]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(sum)

Age    150
dtype: int64

In [93]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,50]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(min)

Age    10
dtype: int64

In [94]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,50]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(max)

Age    50
dtype: int64

In [95]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(max)

Age    40
dtype: int64

In [96]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply('mean')

Age    26.0
dtype: float64

In [97]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,20,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply('mode')

   Age
0   20
1   30

In [98]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply('sum')

Age    130
dtype: int64

In [99]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,40,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(sum)

Age    130
dtype: int64

In [100]:
h={"name":["A","B","C","D","E"],"Age":[10,20,30,30,30]}
df=pd.DataFrame(h)
df
df[["Age"]].apply(sum)

Age    120
dtype: int64

In [101]:
A={"Name":["Honey","Jeet","Sunny","Pramod","Ravi"],"Marks":[78,34,59,79,88]}
df=pd.DataFrame(A)
print(df)
df["Marks"].sum()

     Name  Marks
0   Honey     78
1    Jeet     34
2   Sunny     59
3  Pramod     79
4    Ravi     88

np.int64(338)

In [102]:
df["Result"]=df["Marks"].apply(lambda x:"Pass" if x>50 else "Fail")
df

     Name  Marks Result
0   Honey     78   Pass
1    Jeet     34   Fail
2   Sunny     59   Pass
3  Pramod     79   Pass
4    Ravi     88   Pass

In [103]:
def myfunction(n):
    if n%2==0:
        return "even"
    else:
        return "odd"

In [104]:
myfunction(42)

'even'

In [105]:
myfunction(41)

'odd'

In [106]:
df["category"]=df["Marks"].apply(myfunction)

In [107]:
df

     Name  Marks Result category
0   Honey     78   Pass     even
1    Jeet     34   Fail     even
2   Sunny     59   Pass      odd
3  Pramod     79   Pass      odd
4    Ravi     88   Pass     even

In [108]:
D={"Name":["A","B","C"],"phys":[60,80,90],"Chem":[22,79,65],"Math":[45,82,90]}
Result=pd.DataFrame(D)
Result

  Name  phys  Chem  Math
0    A    60    22    45
1    B    80    79    82
2    C    90    65    90

In [109]:
Result["Total"]=Result.apply(lambda r:r["phys"]+ r["Chem"]+ r["Math"],axis=1)
Result

  Name  phys  Chem  Math  Total
0    A    60    22    45    127
1    B    80    79    82    241
2    C    90    65    90    245

In [110]:
# def myfunction1(n):
#     return row["phys"] + row["Chem"] + row["Math"]

In [111]:
Result["Percentage"] = (Result["Total"] / 300) * 100
Result

  Name  phys  Chem  Math  Total  Percentage
0    A    60    22    45    127   42.333333
1    B    80    79    82    241   80.333333
2    C    90    65    90    245   81.666667

In [112]:
def per(T):
    return T/3

In [113]:
Result["%"]=Result["Total"].apply(per)
Result

  Name  phys  Chem  Math  Total  Percentage          %
0    A    60    22    45    127   42.333333  42.333333
1    B    80    79    82    241   80.333333  80.333333
2    C    90    65    90    245   81.666667  81.666667