In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("myrgroup.csv")
df

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [3]:
df["city"].isin(["Bhopal","indore"])
print(df)

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [4]:
df[df["city"].isin(["Bhopal","Indore"])]
df

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [5]:
df[-df["city"].isin(["Bhopal","Indore"])]
df

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [6]:
A=df.groupby("city")
for i,v in A:
    print(i)
    print(v)

bhopal
        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
5  1/6/2024  bhopal   rainy  21.0       20.0
indore
        day    city weather  temp  windspeed
1  1/2/2024  indore   sunny  32.0        4.0
4  1/5/2024  indore   sunny  35.0        5.0
ujjain
        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [7]:
df.describe()

            temp  windspeed
count   8.000000   8.000000
mean   26.125000  11.625000
std     7.661359   6.947507
min    19.000000   3.000000
25%    20.000000   4.750000
50%    22.500000  13.000000
75%    32.750000  17.250000
max    38.000000  20.000000

In [8]:
A.get_group("ujjain")

        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [9]:
j=A.get_group("ujjain")
print(j)

        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [10]:
j[["temp","windspeed"]].sum()

temp         57.0
windspeed    20.0
dtype: float64

In [11]:
j[["temp","windspeed"]].max()

temp         38.0
windspeed    17.0
dtype: float64

In [12]:
j[["temp","windspeed"]].min()

temp         19.0
windspeed     3.0
dtype: float64

In [13]:
j.agg({"temp":"sum","windspeed":"min"})
print(j)

        day    city weather  temp  windspeed
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [18]:
j.agg({"temp":"sum","windspeed":"min","city":"count"})

temp         57.0
windspeed     3.0
city          3.0
dtype: float64