-- Pandas:Excercise

In [32]:
import numpy as np
import pandas as pd

Q.1 Load .csv file

In [33]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

Q.2 Display top 3 rows

In [34]:
df.head(3)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74

Q.3 Display last 3 rows

In [35]:
df.tail(3)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

Q.4 Find number of rows and number of columns

In [36]:
df.shape

(6607, 20)

Q.5 Get information like total number of rows,total number of columns,data types of each column and memory requirement

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6594 non-null   float64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6604 non-null   float64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: float64(2), int64(5), object(13)
memory usage: 1.0+ MB

Q.6 Check null values in the dataset

In [44]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                   13
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              3
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

Q.7 Get overall statistics about the dataframe

In [45]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6594.000000,6607.000000,6604.00000,6607.000000,6607.000000
mean,19.975329,79.977448,7.029421,75.070985,1.49364,2.967610,67.235659
std,5.990594,11.547475,1.468528,14.400397,1.23068,1.031231,3.890456
min,1.000000,60.000000,4.000000,50.000000,0.00000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.00000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.00000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.00000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.00000,6.000000,101.000000

Q.8 Find unique values from the gender column

In [60]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

Q.9 Find the number of unique values from the gender column

In [62]:
df['Gender'].nunique()

2

Q.10 Display count of unique values in gender column

In [63]:
df["Gender"].value_counts()

Gender
Male      3814
Female    2793
Name: count, dtype: int64

Q.11 Find the total number of students having marks between 70 to 90(inclusive) using between
method.

In [64]:
df["Exam_Score"].between(70, 90).sum()

np.int64(1603)

Q.12 Find average marks.

In [65]:
df['Exam_Score'].mean()

np.float64(67.23565914938702)

Q.13 Using apply method get increment the marks of each student by 5

In [71]:
df["Exam_Score"] = df["Exam_Score"].apply(lambda x: x + 5)
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,1,92
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,0,86
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,1,99
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,1,96
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,0,95

Q.14 Count the length of student name.

Q.15 Replace the male by 1 and female by 0 in gender column

In [70]:
df["Gender"] = df["Gender"].replace({"Male":1,"Female":0})

df.head()

C:\Users\Asus\AppData\Local\Temp\ipykernel_24672\2865535459.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Gender"] = df["Gender"].replace({"Male":1,"Female":0})

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,1,87
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,0,81
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,1,94
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,1,91
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,0,90

Q.16 Drop the column gender and marks in given dataset

In [74]:
df.drop(["Gender","Exam_Score"], axis=1)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near

Q.17 Sort the data frame as per the marks column.

Q.18 Sort the data frame as per the marks column as well as gender column.

Q.19 Display the name of those students who scored 89,70,65,60 marks.

In [75]:
df[df["Exam_Score"].isin([89,70,65,60])]

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
15,17,68,Medium,Medium,No,8.0,70,Medium,Yes,2.0,Medium,Medium,Private,Positive,4,No,High School,Near,0,89
25,21,62,High,Low,Yes,6.0,54,High,Yes,0.0,High,High,Public,Positive,3,No,Postgraduate,Far,1,89
29,18,66,High,High,No,4.0,51,Low,Yes,2.0,Low,Medium,Private,Neutral,2,No,College,Near,1,89
36,21,65,Medium,Low,Yes,7.0,91,Low,Yes,2.0,Medium,High,Public,Positive,3,No,High School,Far,0,89
39,21,65,Low,Medium,Yes,6.0,98,Low,Yes,1.0,Medium,High,Public,Negative,4,No,High School,Near,1,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6577,14,73,High,Medium,Yes,6.0,57,High,Yes,2.0,Medium,Medium,Public,Neutral,4,No,High School,Moderate,0,89
6578,22,76,Low,High,No,5.0,65,Low,Yes,0.0,Medium,High,Public,Neutral,3,No,High School,Far,0,89
6593,16,75,High,Low,Yes,10.0,53,High,Yes,0.0,Low,Low,Public,Positive,4,No,College,Near,0,89
6598,9,87,Low,Medium,Yes,6.0,64,Medium,Yes,1.0,High,Medium,Public,Neutral,2,No,High School,Near,0,89
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,1,89

Q.20 Remove the duplicates Rows if found and store only last unique value.

In [78]:
df.drop_duplicates(keep="last", inplace=True)